//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36315
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavePlayer.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WavePlayer.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color.
        /// </summary>
        public static string Accent {
            get {
                return ResourceManager.GetString("Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color not found.
        /// </summary>
        public static string AccentNotFound {
            get {
                return ResourceManager.GetString("AccentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add track.
        /// </summary>
        public static string AddAudioCommandName {
            get {
                return ResourceManager.GetString("AddAudioCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string AlbumsCount {
            get {
                return ResourceManager.GetString("AlbumsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization window.
        /// </summary>
        public static string AuthorizationWindow {
            get {
                return ResourceManager.GetString("AuthorizationWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast audio to the user status.
        /// </summary>
        public static string BroadcastAudio {
            get {
                return ResourceManager.GetString("BroadcastAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha.
        /// </summary>
        public static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2014 WavePlay. All Rights Reserved..
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equalizer.
        /// </summary>
        public static string Equalizer {
            get {
                return ResourceManager.GetString("Equalizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string GroupsCount {
            get {
                return ResourceManager.GetString("GroupsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading account information.
        /// </summary>
        public static string LoadingAccountInformation {
            get {
                return ResourceManager.GetString("LoadingAccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop.
        /// </summary>
        public static string Loop {
            get {
                return ResourceManager.GetString("Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My audios.
        /// </summary>
        public static string MyAudios {
            get {
                return ResourceManager.GetString("MyAudios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My friends.
        /// </summary>
        public static string MyFriends {
            get {
                return ResourceManager.GetString("MyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My groups.
        /// </summary>
        public static string MyGroups {
            get {
                return ResourceManager.GetString("MyGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now playing.
        /// </summary>
        public static string NowPlaying {
            get {
                return ResourceManager.GetString("NowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only foreign artists.
        /// </summary>
        public static string OnlyForeignArtists {
            get {
                return ResourceManager.GetString("OnlyForeignArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went wrong.
        /// </summary>
        public static string OopsSomethingWentWrong {
            get {
                return ResourceManager.GetString("OopsSomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the code shown below.
        /// </summary>
        public static string PleaseEnterTheCodeShownBelow {
            get {
                return ResourceManager.GetString("PleaseEnterTheCodeShownBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular.
        /// </summary>
        public static string Popular {
            get {
                return ResourceManager.GetString("Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WavePlay.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W  A  V  E  P  L  A  Y.
        /// </summary>
        public static string ProductNameTitle {
            get {
                return ResourceManager.GetString("ProductNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to explore your music world with us.
        /// </summary>
        public static string ProductSlogan {
            get {
                return ResourceManager.GetString("ProductSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations.
        /// </summary>
        public static string Recommendations {
            get {
                return ResourceManager.GetString("Recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove track.
        /// </summary>
        public static string RemoveAudioCommandName {
            get {
                return ResourceManager.GetString("RemoveAudioCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find more tracks of this artist.
        /// </summary>
        public static string SearchByArtistAudioCommandName {
            get {
                return ResourceManager.GetString("SearchByArtistAudioCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find more tracks with similar title.
        /// </summary>
        public static string SearchByTitleAudioCommandName {
            get {
                return ResourceManager.GetString("SearchByTitleAudioCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show lyrics.
        /// </summary>
        public static string ShowAudioLyricsCommandName {
            get {
                return ResourceManager.GetString("ShowAudioLyricsCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        public static string Shuffle {
            get {
                return ResourceManager.GetString("Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with VK account.
        /// </summary>
        public static string SignInVk {
            get {
                return ResourceManager.GetString("SignInVk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have a VK account? Sign up now!.
        /// </summary>
        public static string SignUpVk {
            get {
                return ResourceManager.GetString("SignUpVk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song&apos;s lyrics.
        /// </summary>
        public static string SongLyrics {
            get {
                return ResourceManager.GetString("SongLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background theme not found.
        /// </summary>
        public static string ThemeNotFound {
            get {
                return ResourceManager.GetString("ThemeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no tracks in this album.
        /// </summary>
        public static string ThereAreNoTracksInThisAlbum {
            get {
                return ResourceManager.GetString("ThereAreNoTracksInThisAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks.
        /// </summary>
        public static string TracksCount {
            get {
                return ResourceManager.GetString("TracksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled error has occurred.
        /// </summary>
        public static string UnhandledErrorHasOccurred {
            get {
                return ResourceManager.GetString("UnhandledErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersCount {
            get {
                return ResourceManager.GetString("UsersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VK Account.
        /// </summary>
        public static string VkAccount {
            get {
                return ResourceManager.GetString("VkAccount", resourceCulture);
            }
        }
    }
}
